version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/ultramozg/golang-blog-engine
  lll:
    line-length: 140
  misspell:
    locale: US
  unparam:
    check-exported: false
  whitespace:
    multi-if: false
    multi-func: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - errcheck
        - gocyclo
        - gosec
    - path: testutils
      linters:
        - errcheck
        - lll
    - path: _test\.go
      linters:
        - unparam
      text: unused-parameter

