run:
  timeout: 5m
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/ultramozg/golang-blog-engine

linters:
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: testutils/
      linters:
        - errcheck
        - gosec
    - text: "G306:" # File permissions
      linters:
        - gosec
    - text: "G402:" # TLS MinVersion
      linters:
        - gosec
    - text: "unused-parameter"
      linters:
        - revive
    - text: "receiver-naming"
      linters:
        - revive
    - text: "exported:"
      linters:
        - revive
    - text: "blank-imports"
      linters:
        - revive