version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 140
    misspell:
      locale: US
    unparam:
      check-exported: false
    whitespace:
      multi-if: false
      multi-func: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - errcheck
          - gosec
          - unparam
        path: testutils/
      - linters:
          - unparam
        path: _test\.go
        text: unused-parameter
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/ultramozg/golang-blog-engine
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
